//
//  HelloFlynnActor.swift
//  FlynnActorModel
//
//  Created by YuCheng on 2021/2/10.
//

import Foundation
import Flynn

class HelloFlynnActor: Actor {
    private func _beSayHello() {
        print("Hello Flynn")
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension HelloFlynnActor {

    @discardableResult
    public func beSayHello() -> Self {
        unsafeSend(_beSayHello)
        return self
    }

}
