//
//  TestActor.swift
//  FlynnActorModel
//
//  Created by YuCheng on 2021/2/10.
//

import Foundation
import Flynn

class TestActor: Actor {
    private func _beTest() {
        print("aaa")
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension TestActor {

    @discardableResult
    public func beTest() -> Self {
        unsafeSend(_beTest)
        return self
    }

}
